spring:
  application:
    name: ai-demo

  ai:
    vectorstore:
      redis:
        index-name: spring-ai-index
        initialize-schema: true
        prefix: "doc"
    model:
      chat: openai
      embedding: openai

    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma4:e4b
    openai:
      base-url: https://dashscope-intl.aliyuncs.com/compatible-mode/v1
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        model: deepseek-v4-flash
#        extra-body:
#          enable_thinking: true
      embedding:
        model: text-embedding-v4
        dimensions: 1024
  data:
    redis:
      client-type: jedis
      host: localhost
      port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web_school?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: 0709

logging:
  level:
    org.springframework.ai: debug
    org.starry.aidemo: debug