spring:
  application:
    name: ai-demo
  ai:
    model:
      chat: openai
    ollama:
      base-url: http://localhost:11434
      chat:
        model: gemma4:e4b
    openai:
      base-url: https://dashscope-intl.aliyuncs.com/compatible-mode/v1
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        model: deepseek-v4-flash
#        extra-body:
#          enable_thinking: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/web_school?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowPublicKeyRetrieval=true&allowMultiQueries=true&useServerPrepStmts=false
    username: root
    password: 0709

logging:
  level:
    org.springframework.ai: debug
    org.starry.aidemo: debug